export const COMMAND_KEYS = {
  BACK_TO_MAIN: "backToMain",
  START: "clickStart",
  OPEN_MINI_APP: "openMiniApp",
  USER_AGREE_TERMS: "clickAgreeTerms",
  USER_DISAGREE_TERMS: "clickDisagreeTerms",
  BUY: "clickBuy",
  SELL: "clickSell",
  COMING_SOON: "comingSoon",
  SELL_TOKEN: "sell_token",
  TOKEN_INFO_CALLBACK: "ti",
  CUSTOM_AMOUNT: "customAmount",
  CONFIRM_BUY: "confirmBuy",
  CUSTOM_PERCENTAGE: "customPercentage",
  SELL_INITIALS: "sellInitials",
  CONFIRM_SELL: "confirmSell",
  WALLETS: "wallets",
  EXPORT_KEYS: "exportKeys",
  WITHDRAW: "withdraw",
  TOKEN_INFO: "ti",
  HELP: "help",
  REFERRAL: "referral",
  CLEAR: "clear",
  BRIDGE: "bridge",
  SWAP: "swap",
  CROSSCHAIN: "crosschain"
} as const;
